### ISSUE TITLE
Jar in the newest release missing

### ISSUE THREAD

**Issue by 1ue999** [Redstonneur1256/Mindustry-ModLib#5]
its an easy fix: copy the zip and change the extension to .jar

**Comment by 1ue999** [comment]
oh nvm that zip is the srcecode

**Comment by Redstonneur1256** [comment]
Sorry for not replying sooner, the build was indeed missing due to Jitpack not keeping older versions of arc causing the build to fail ([actions log](https://github.com/Redstonneur1256/Mindustry-ModLib/actions/runs/6682080986)). I was working on updating the buildscript for the project and wasn't able to fix the issue at the time. This is now fixed and you can download the lastest release [here](https://github.com/Redstonneur1256/Mindustry-ModLib/releases/tag/1.4.9)
